---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-titan-hdd
  resources:
    requests:
      storage: 1Ti
