---
# Static PV pointing to migrated data on Titan NAS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wyoming-whisper-data-titan
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 10.20.30.99#volume1/k8s#pvc-29256e06-1b59-43ed-a2f6-6f2b4e106708##
    volumeAttributes:
      server: "10.20.30.99"
      share: "/volume1/k8s"
      subdir: "pvc-29256e06-1b59-43ed-a2f6-6f2b4e106708"
  mountOptions:
    - soft
    - timeo=30
    - retrans=2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: wyoming-whisper-data-titan
