ansible_become_pass: ENC[AES256_GCM,data:HB9gvCDsN8Ii,iv:n9Z2inruBo0aMlPYTciiTIx9jZ5qvQAF3IVlz+U5z8A=,tag:vTS2gpL2DweDiTnAuhWQQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2K0U2WHQrU2ZXTlBScFlM
            UFFlMTdUelltNnBoYUZxMU1rZVl4UUtyb3lVCkdJVDQ1bW00S3g5Rk9Wb3B2OXZa
            SnhIM0VYR2hrUXFKUTZDZ0dXQ2Nxc1kKLS0tIGx4QjJwMUhWVTMyOUFtcEh1NXBS
            ekVWVExPU21VT05YUnhBaHdvaDlZSXcKmqzKwuaqFjEmTDIqwplFPaZqbyp2jMHg
            m1iLUIWLbRtfR8cG25WaCQiph0H4L6q7nP/wiNSiEPX55vks2JOymg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:dnk3enmzleuUX7MNrcsXMF8ahOApUoAL1fm8Kgjz6u0bsyvixeBKmz/HzZvgTDCyZobOafDbZDzlsEOAOXza7faKCQArfcFaJxrmsI1GM/K8GGRAIlOhyrKkLGJQ18fEbAjrNuWdLF5lnavKu2tJG8kUg+Y/0uuPXvTiEUwx3bk=,iv:AOJASGY7PVEgGWMOLn7UYjAy3+c4vdLeiEZKBQfflr0=,tag:BHzHK4bTdiiJ2zr4hB4rSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
