ansible_become_pass: ENC[AES256_GCM,data:VMy8cB6u2mq/,iv:WTB8wA+66Df5m6TdfU1Bn3Mlic6RqW6JtEKGF/KUmgU=,tag:nfHiA6N656NLrbqHjUvjpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWEJWeU41ZzFCdEcwaVZ6
            ak14TWp1UUNDaTBCVzVzMkZHbzgxNnlFTTBzCmk0RXJUL3ZVMWxwUmNEcitUM0x5
            RlFIMjc1OEdPWU5JNXNTTnB5RFFZNDgKLS0tIFlpeU1oNE1LajdsVnhHaXdzQmRT
            MzFKQk9aTlUyZlI4dU51N2l0Qlg5MEUK0oGUcLxYRszPD9s+BTXDhndflYvnUKI9
            pEjdHbquitDBzf2A+PahKZTnAR3vKYJ+55/XVnDVxiOr1jSLegLy4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:kCGtMnac9poKsbhYUsstsx08Bk6+SuVXzAsdHy2Umv0MTrfjLvALvZLNdE9ebSep1d8i9qKbHUxAFlfMVXsZWq5KAXTkdnCpqInoKZa9QISf7kRzqwKAEW/4YDXWeyXBzdlQOCAcHvqwCJ9cqx92L7gGK8DKKRpzRpIVoY/D9UE=,iv:l9Llyqb+gkesJkborvHMWxtdZ2/56JC8VgJyWysZX7A=,tag:WyIiyfMBpBOLUh2sy+jmnw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
