ansible_become_pass: ENC[AES256_GCM,data:TtuBAC+R9lbn,iv:Qeo1dhQtTrYH+c9tKVe4RlRWqb8q+UrWPxBsBLrlCMk=,tag:SLIRfDRJxKJhP9jso/0S9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NXR6WmZmMmx1T3FXeWpi
            SU0vdmd6S2lwY2dXa0lxcTZtRlZZd1B5MzJjCngwTjhJM2lSaEFXSFkybnZPOS9N
            MVhZUUtjUEJLblU2ZXdsUHhoenRyT28KLS0tIFJZRG50dDVsdlo1QUd0ZkR5WUhj
            Y1BKbnZOa1paMks2OHVscXRYSVNCZkUKAl5uWxwqwvKN5nPf4FXnZrthTRTfSRWe
            oTnE1Ac4PYlNykQ7tSBdbyZaNmeGwr6HBsgR1OMyPl9bADDqJXkvPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:EoadosgbFwsYbK+vnsDyjvWAzO7rfBuLHopywjqpoElzeEGzr/+EnpVsQ4N6Ha6VN2aTAbSV+HrLekil8P7IUqtiKtskcq5fEutH8L9Ynx/3xaOIgiA+zNS1WwQFRDaM+agXFKFUhpiNKwSPQDADzv+Mnu4I1bdQLftxCe9/a+4=,iv:FvvOdUrUg1MmgrkgdR2s5sv7Mgc6L2ZVgxqswzWFYBM=,tag:uPz1M9eZIIyJ3ox5CIdimA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
