ansible_become_pass: ENC[AES256_GCM,data:QmkbxmDgrf75,iv:lZzLNwmhR8BuC7/H6lcHKbvtdoEZodAFAuAckFoKFSs=,tag:R/Nmxdpag5RxErYWgVPNuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUVUyK1c4OFlHbkwrTWh6
            T2JFM2xuZlRlVHdaQ3FxekM3b1ZJV2RkUUVRCnZsYkgxU3YzWXF0RExHS01GYjVY
            ZFUxMGEveWR6dEhtSVBob1hRc2FEdVEKLS0tIDhLVDlxejJVTEpjM2dJK0FHK0dt
            Ti9QUXhIZk11Z3QxM01WMnB3bjBNSXMKzMWihkq18T+4pNlAkOd6tOjqgzVIb99y
            eSh9Zb9P7ec9JN7KiBWk/TPhE8FowWiLWt8zv61K93s9aiJmFZKAQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:msYfkhn5PVeg76wVmOdEYobCsMxG3wFq4VImNTU0UAnOnQYRgk7BR5M0wOXQ4pDRs1hfHJKOkYC7h6qiappo0/uIh915DI51SHvFhLLg3hJHtvG8MKwvqT/gpJv02FtmFN2zYXNCkXxhXOc02Jg4l0ndnKfkLIJKGA9KsxD+jmg=,iv:v/FcNhHVuq2dJY0sR67be8VQppv5BW5hujs+6HDeZOU=,tag:KS+5KOgAMty+8y1X85L7dg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
