ansible_become_pass: ENC[AES256_GCM,data:gyAYKPhI6bW+,iv:+wKMqNwUCx+rSCgsl98dKziOl4KzgbUOnyvQtCLxczk=,tag:Gaz81x3HQQKaviBRnylLzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RnNSeGVwNGtqVHZ0elph
            SEZOWkNtSEREcWhpdlpBcCtmc0tuWDdnUkQ0CkJMc1RZZUE2bVRxTjNSN1o1clgy
            bU5iKzVob2FpUWdMSTQ1KzJGcVg5VXcKLS0tIHhYOHZPd2U5Y000NGxHUy9uNk9J
            YWR3Yi8zVkQyS3RLcU5NYW5KbzcxK1kKSJ2I0pfnxtysvK3B9HrtmfNpFTxWKb0s
            SgCOCYg7PO9W0MPLP8F96wWc2f2bv/SEnnqsjGQkGKUSfSyyh/4hZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:86RgW+qrmpsDmAt7927NucPC5D4K2v6My9L/C3vuweOC1JXRbQd3Heek8GeeuP/laZBP+2Ql9lEtxsAMAwyU0kDWydGU0jAqajaZqmjh29UkvByqOio1DTx/gUlW8Eh5RHpDD8+3oyOblUaiQPINPYS40Wh/5KOkb5hWxVXug6Y=,iv:reypSSPaxcLgM5/R88Qfeo/gxCl3xkiLPNpIUq3a618=,tag:Adpal8akiouQDb6D1GmA3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
