apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:dktf7gM1p4v8,iv:WwZyRxFA4dX9mbk/FHVH+0n+yQCNLnt69x4NTm6YcKk=,tag:T/m5rdwu9Wym3lI8+94Dkg==,type:str]
    admin-user: ENC[AES256_GCM,data:2NSiniQ=,iv:RF6g9AKpO2HcdGgjPoahnr9M7cXaZISzI9xlbXQGfQ0=,tag:TG8LepjSEFWHXc8b0bQirg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLV3QxUHU5U3dhbDF6SXdw
            VW54YVNMc2tpb3JDazhBNUZoUDhMN01CdGg0ClltU0UxSG16YWtaeURrSWcwU2dK
            VVNTL0QzSTA1bnlQQ1hGMkZ2V1BUWjgKLS0tIG9XU1V1bjV4M2s4Rmdya0QrZkhC
            VGR6RVdMYys0UldsQklIcGhWWUQ2YnMKnD/f0gi4VOi+dQT//wE1VtJlm7BNBnCn
            LdjVrCZFCkYgjOndwriDd3QT1+FyfUtP28eTepHivFtSip4eyHv2/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:ndTysP0q08YGNayI85bEofuOtryroN83nphCYmIz6CFS/FDozn5M1JNHlHt7PpBY1mps0MtQMlExBP7B+Ihgol0AAjVr63oxlIPGI/10Q8y/6ulFcg8nnpFiD7SY2gC4KYOowbbD2SgdDL1AZXYUsL3ga6n89CAazQPs49QkGyU=,iv:1sqeZptIE6T612hfD6R1KhcP/G1rWelJfI+CsNkFZpM=,tag:XwIxPEP8RV9lJXgYmyDVLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
