apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:St+k59rlo/LIRcvR71IH4OGyXDSTcwvi,iv:PogcC6nqkscrk6AxRjjMeXk3kSeULzKn4TGxU44UCwY=,tag:PDqJv/ObrMOMaP/f0wH+yQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYUFleUtNQUFqYm9tdHJC
            VzFsSml3bmVIdjQ4M1hkcGI3RXN1NDBvRHhnCndaWVNBbEJYbE5mbjU2SDAwbUxt
            ZEhjTkd0aUVlbzlaUE9Ma1ZveEI3YzQKLS0tIGVQM1N1eGNpeTdQT2wxenRjRUpq
            NjY5Yzc4QnVCdU5pRWhYK3VhZTZYNXMKSENaDcHD2gnR7Q+PbVs9y5cNav1AtL0Z
            GREEavnTHDaXunxwCNYrHHr/6rit0r7ud/JpOg89LITJKkjlX6gQ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:P7xXoV1MOBFwf3cGfHk4ppUTgXW8qjxyZegqyEljK/DTpcan6OiTb5ip+/ECQXKFOxlT1aZq9yUJNBqru3wzsbZbue0O0P/sfUhbj/McQUjjkpfMXbPbnnEgciPg78hn+OL6ZwAavWKlrx/HPyWyu1Z0UjiQXEF3PLWz6zQZSWc=,iv:2Is6O0DpixkFb0MIq6AsZvQY0fi3ejSPsXiZB1eiWlA=,tag:pgzDlAKnAHqLQSq1IMgh2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
