apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:y1iM22on6JqYfM0rja+z1dulxIF0dhxLRvmUVAUwdDJTVed7BW1gtw==,iv:NEF/bgDJP666du7z661QBSJgJUpwBxVcKjYXr4TFil0=,tag:t1qo4Bji7H/dqBapyAgfQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNU5PMG1pQ2RvUjNhRHBB
            akNKNWl6RWVsRUhISDc0b0E3OFZ2Q0F3VkZVCmp0d0VIM011ZUs0eDU5RVAxWjY5
            MnZ5alF4cFVJYk1JVGtkYm5EOCttNGcKLS0tIGhpM0pMaG5nV0NDZHJYaVR1SUJL
            MHNYL2g1VHN5MU9HWVZCVThEeDFFZGMK1kP9A0zc0S9eoGjR3kxUp3Al3BgGC2GN
            S9+wi7lKm3LZoU3xExokj/bKmJVDNLZ0p5wQ95zeHPmb8LMvntpAeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:U5+wN3UHwEzkbCaHzS6lTJqtqEPMgh5TMSxAAGePeS2m4epcvmkHuCLJRm4W2Fd6HM7JZxfNgEdfgvpjtvDutJqtDJpvB23lM7soD4SOQa5kloP9mwzoj9qHGheBgpvqgFZB5V+5LLOcu50syNLggWvu78iQKrt4/B5WcAj21I8=,iv:RV9tmQd8+KUHC8PeoLNAYHxmLtLYH1L2PXM6RpWPX4Y=,tag:GJ6Qca8r7OcbOkycOq8ReQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
