apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:vlZUzrzCyO7CgmowIgFbVbbaV8Tuh5mID1sg8DosIyjnYUhq7NoXvg==,iv:IdlOIxLqrMD7SMUlqKE0Cls3OZQEjdhUn6KmhfB6nrA=,tag:W1dxcEtE6gDbXHyHnZREZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdnllL3RkeXlyMkNhaXZ6
            NHUwT2dPZVRSdGFoeFRsVStaWjJLTFFhVDFzCkp1N1U2dFM0dG0zTXltYVM4L083
            MThqaWFOZXZxcnd5N0huam5tQUJyZVEKLS0tIE1IMVRKdkRFL01LVHNGMjFRRmZo
            cGJSTHM2THM0WTZtWi9JTlM1bWxJNGsKyIIWuHMGSg5fFYLv5XE6W2bPo657G/9p
            56kJLOIlTpln5jaO2R2xqZQQve1xXbMmQbb4b4Uqr123rpddw67jsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:FpZp8jt6teCvTWC3amGinbaDCrTzzqfo7/4/9GRzb/ms8LeVYTGWEWCQrnFRv/cXGg4C1huDB7WRVSONRiFI67C5w8xkvVNT+3w+7avAshzPz+kVUBs9tdK7NSxVlvGaR1UarYzNf1eihmBEoFl5m4WtC1dgHx+mNbbKPW+mjg0=,iv:UNUtYLHLNMBMunPgejGGGicDsXnrR8jxK5utBrIIpTA=,tag:IS/khsGVK7eIHtlDM0GZvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
