# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: recipes
    namespace: home
stringData:
    postgresql-password: ENC[AES256_GCM,data:sZBdGSoVcq3fYNej,iv:I5IAj81wJm/yUljfJ97kj1+ByFSVaLZ0rgp4BNdbx6w=,tag:QG3evT3iPvhtX/Aba6jNtQ==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:/LYrn+XMou+0znXp,iv:aP9AHPATZb7YvVkUSkPcNzTuqoTjVI1bc5aYU1yufyw=,tag:ahtO8jtQqmlgnwuwnPxSuA==,type:str]
    secret-key: ENC[AES256_GCM,data:dGhL9RaOPBMnGi9UjWnS2W8cXkZDM4BLQJCQQnHSKj9HEIdIzLefL2kWWQw8hlAreqjsnHwG5mROsgOxPqCncjWHF+5SAmx17yfRGIIyU4syL0jhxYCwvA==,iv:YaYd53IvCNEqzcMEndvDcYHl2G6Rv8ydAhDVJuBA3LA=,tag:VKnqjUbYtY6FoRbgon+9CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UG1PTW0vclh4d0ltWEM2
            VGhaVjlyYTZydjA1RGZUczYybWNkRndWNncwClBDdGZyaXdndmFwQnVZUHV1bklr
            V09MNUNKWG9xUlhzSDZ6bHVKdTVkdUkKLS0tICtyaytLUyt6TjVZNFVlZk1zdlBT
            YVB1VWE0MFloa3U1Nlc2U3psOU5mSUEKHSbZXn6UlBa3hZYWYE1o3bgxaV5hxT9r
            w9m1SBjG6BgMc1WgGhtEZqjuN4oCQD/giKVVbyhBq0qq9bng8wWg7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:+jFglBClBwb/w568TDuRMMDAsDFEqM8lsgu11i0NnAC3pzsSnqlkrviJfpe/aWh6YvDnvK/Zplepdwl/SShKtkLaPNsEikzhB8+Sc238H2nwHzQPInN4DkSPIUCBBAl3r18OxRJjRT1Ra4todBtAfJD5U25TgUf28o899aOlxrQ=,iv:Czubh+UFgPLHmogA6X65lAB/uMh8QqpTnryfboRTZ1k=,tag:0Ec8thOWEZe1317OX5uOhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
