apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:eKmh+SkWg66723Wfe5KHrnY7CFGJbV1DcRxdYkc6E/Xde7bbGlcJN6Uw393Ftvpv2QouLGxmd9oNUmZE,iv:9NG6GyDCaMuWChchNBiof1o4tOBrVDxoMndiWRtpZBs=,tag:c9FLiQelRdoTfujcn9y5gw==,type:str]
    username: ENC[AES256_GCM,data:+qoR5kE=,iv:ZzNbFaZcEe96AOgvss+k/DX6r7BKSt1S3kqTAfapGF4=,tag:+driepn5sQtNXehL8IQ45Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR1B0RHUza1hRZmk4TWhX
            T0VCSGw2WUJtMU1nVnErdVI5UlQwODROenc0CkpRamcxcnhaLy9lU3BOWmtFZ08w
            d1o0d2dPT3pYQ2NnUjlxTnZvSEl3b00KLS0tIHRVdHdackJIbVBZZzdtb1BvTHBs
            TXVaOFVDblVZcG1PdlgxYzIzWS9UMm8Kv65PCxITM0F1Bv8rxTuL3TDIlO1XqF7F
            75r16RO1/Fnm/mnOgeSr6UZ+8q2LHOgEtGsQL17CkLAlfw416zG+4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:uWy07NfdKhSUpoMOB7emDLtrzEwrpoZtWCMEgqK9AH8szfHVvVMAsuXktEtnjv3RRI21w9wGqSs7/SnWkDxx55XfLfmjVeMSpPn4jVTzm0EPsofTGMWDejJxQCY5K/lxbcfjP9dPAQj14tG3osU31m6BAlKFZA6fbwIQ7LTE2Uo=,iv:94gW8OQQmLLhvALds1VPMVuwYxHO7fA2n2qdYKbsQj4=,tag:IL0VWebs8XIL8MayAX7s7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
