apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JelPo7/UU3QsZKsBbNoPbQqHrjHV,iv:j3KXaU68wtdjxpBgFI9vXTl/yXog2YeSI9fcF2zzE8U=,tag:9q9/bny7ZrisGCQP6sgnog==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AaHbbtsj1jJdKE1dTUlk1rjCwFRCEYL6OXH54FICvMJe469s,iv:U4k8VnoCKsgohCMxB0xWKPgHnNo+6dABsTmfB/QulyU=,tag:Bm6oR7/QS1BzNc/MVxi6WQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:foGGlQHwLYIXKGqxVA==,iv:k/738+xTs0cNVrGI7IqvuHVmpsOejalM5oh4QSN2H7M=,tag:yaHXjznT9FjhNuNnI8H2lg==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:rzx9sxnmCO6pcejWB/VkrrEg,iv:BlAmjrroZiAY1V+EJy+fz1FRN0wJ6oZspOuOGAfydPg=,tag:5eomoqAiXvd2bT0wTx16eg==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:Hk87jmxYlt68L+V/BGk=,iv:qqQoc7sxeIuFDGJjifs+/YokK8X4FfdNVAKmrZbAagY=,tag:fmCfr1IDcSe3txax34jVhg==,type:str]
    SECRET_PAPERLESS_NGX_SECRET_KEY: ENC[AES256_GCM,data:tscfeMeH89vffdhEJxo=,iv:HrRXlAF79dWblnQ+LXR6aXLQo3/Sl2sAybIPKek+FJ0=,tag:ZBx+LNQ4dGD8FC4zodqJsA==,type:str]
    SECRET_SES_SMTP_HOST: ENC[AES256_GCM,data:Ii2z/2INWLLF2NAQYPQcdKt9Rpo93L/2c10PKvFdIkHXdg==,iv:uAySXQJXhGbFUwoUlgoXK9tqDZZq53Oe1t2oii2KWg0=,tag:/3XqoRWyvqP95oQg8/30EQ==,type:str]
    SECRET_SES_SMTP_PORT: ENC[AES256_GCM,data:hTvZ,iv:GSN9/7AbysxKdzRwFgrnl1NLGkK4oX4j5Dxa2LD4GbY=,tag:L4KKmYz0koG622+E7/DrxA==,type:str]
    SECRET_SES_SMTP_FROM_EMAIL: ENC[AES256_GCM,data:6ttcjuIE9wV7G+d1+42DkMR8SJuq,iv:gytQYQFJKkj0/0e1pYahvy59TqW8dcDqknA9MG9XP+o=,tag:ja1w3JzVJWzLNpVZ6pBW4Q==,type:str]
    SECRET_SES_ACCESS_KEY: ENC[AES256_GCM,data:7V811Ay53b7ZcrcQSUaCy1/SQq8=,iv:V5sIWvDARff24KlwjuSgVka901EYqwsAE58IrcBlb0w=,tag:yERMWD0z8FHCqJydJxyEBQ==,type:str]
    SECRET_SES_SECRET_KEY: ENC[AES256_GCM,data:+eihVYyxMb104sorhMz5DcuAWYE8CeGPhvo1xbUZkrz9EdbV4BFTDQ==,iv:d/bEFc+vcrwOvEu3Qe0dLztYVSVUdyjEUNFgjJOd6Ls=,tag:tS9KeSlL5qElFWChzOS+Lg==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:AbvEK49P6Fz7GZiKqOWrmnXGcRM7kJtA9JMu1DXuJ7Ws+HIlqgMPCQ==,iv:QPVHzJMXtguchzJKYHTRkyOs7pKej6XVSDoeR8ZDzmk=,tag:YIgkzPv51FtgpN1SQkxHvg==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:4ahAjn2aGkw=,iv:oAzWBNy6fEHJg7JOQYbCpD56lrk3SbzlS+QoNEJAK/A=,tag:oya3/UiuNUqRlidH9Sr+rg==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:FrV2qBDathMsEB4p1Qenl5ugbA==,iv:0h/69aeZBqYOmzbgP2kKp0rYanWjDZPGoGvcGZdWyhg=,tag:CuVEWS3ajdfH/ctciQQajQ==,type:str]
    SECRET_FRIGATE_CAMERA_AUTH: ENC[AES256_GCM,data:37zcUh/MJTHFu7Kum04lww==,iv:q+Qadx7jd8+MrLOCKmZRhPHfrSCn4cGKCtEe/4nW0oI=,tag:AxE+4QtGGMWhQFrVwApT6Q==,type:str]
    SECRET_VPN_USERNAME: ENC[AES256_GCM,data:jx5zGHom8zpZasCuEWUPngPZBrnu2fS9,iv:pYt8l2fAQg88dlCYq30u6tAqFPsy/lEs8/YsMiQq1xI=,tag:J83fy4NBQVopov6pHLDqtQ==,type:str]
    SECRET_VPN_PASSWORD: ENC[AES256_GCM,data:375k1oMl7T+fL/cC1cXtG3zTuWU0ZkwT,iv:WePqRKwSDRIyQNJxs8xtzUy9YdF+bWJK5hdRYc03bOs=,tag:JyN9bmKSj6qbbpGMIczhhw==,type:str]
    SECRET_SLACK_WEBHOOK_SERVICE_BOUNDCORP_OPS: ENC[AES256_GCM,data:PZ2p8r9ZjpmQblS7JQdEalq5AOu2sWtvxcbBuvGgAUKZlwDilSAy8joJKSbeLg==,iv:HBkped/+l5ODyq6Gc/gvfvuUdL7fi22MuXdFWcTVfPU=,tag:Kdra0vD/XHpv95bfOXZ7Cg==,type:str]
    SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:K7YQVa4sNl/Usp0Ni94VG0J+45E=,iv:D0XJqetbDyohmJiHvaF1fCYkxmnyjGjnuVYcoCNK5Xc=,tag:5glkFpS33aP+Mi/qOlF0nA==,type:str]
    SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4+kNhoTdL1tJScs9LGPqMLu/mkrrU0fi6vaSpD+HYytORBB7qtw1Cw==,iv:/07ju4Au3mM/7RWA+qlSpw0KnDEhC5zIAhF4uRDUO9w=,tag:ri1jDR5ty/BKLwmGGZzRsQ==,type:str]
    SECRET_VOLSYNC_REPOSITORY: ENC[AES256_GCM,data:5cWn/P+pl7iklcDMq2XTRXxwVPYOXa9AtdWrmQ/2bAn2q5RTEFRDRK+BIilGtdTVwrqpzIxNg18EjH76DVpvpHsicjodXBreRZEGaUtjCuE=,iv:OgIQqFgF1QNtrNOxazm+CLQgf7/hjE0eeaI1YV79ZYg=,tag:SXh9HBtwu8iW41+k/il/vA==,type:str]
    SECRET_VOLSYNC_REPOSITORY_CTRL: ENC[AES256_GCM,data:KrUvkwO6POUySGo7uiIPNrveexOIhmBXQqChWLIyM1gnFQaxHQdGYaHf4xJ/loXH/W2bcPPNiUwgciz2wKfe5OJgTH28cOcYeOvBYkY=,iv:r2AtZeq4kwlCE4JN+q1dVDXBtzNfxLDD5f+ZavLVoXw=,tag:hVOWvuHW2zNNAWJzmVxFQg==,type:str]
    SECRET_VOLSYNC_PASSWORD: ENC[AES256_GCM,data:CBotBmKRA0nk,iv:V2MPD5WV5pLgyHrpnk/unpLMjLVwx7K/ECqIYHFjUe0=,tag:seJUsPQjXRqtZoibURFLRg==,type:str]
    SECRET_VOLSYNC_SCHEDULE: ENC[AES256_GCM,data:upWXQEsidzPb,iv:HUDhtt5WuflB5XpDc7JkeDT/Uvp/7Qno6vQxinNjUls=,tag:GlqMRoa2C0FDHtYv4cYnkg==,type:str]
    SECRET_TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:AovKmSrRmus7s1dfeyIjW6iR3WfIbCaH/k2YSv50I/eubRGGzX91P1l6GjDXcbfVSgHIu3ja746u,iv:6qYVpSQ5TxW70tQbN4xvrdRBu4mpbT/fyb2EQXmDoLU=,tag:/5zP0NfZwcyMfiECkAH5Lg==,type:str]
    SECRET_GETH_IP: ENC[AES256_GCM,data:RQsrNvCKztqG15Cj9Tk=,iv:RrvhXA9+sGqEeHA08rp/I5Xs5sC+uxXae3a9NqXUYvs=,tag:hmAwFxw/OmnIyl7sp7zM6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWFJhU3QvdVAzVTQvMlBH
            di9GMFpQa0ZqdlAzbU5aVURMNEgwUG9IVkJnCmV6T0xaL1dQSE5oeU9Db3p0akxK
            Vlo0QnpxVUorQTRCTmgxLzJMd01HMW8KLS0tIDFEWTdFSFloMXJPVFE0b0U0SVJs
            ZVBmNDFubWVRNHZVVnZXWjJtdkJoY3cKZzA3wjCNkcN8RXO4xLcdNZ9GqCVa63AI
            IEhlpuD2prfQ4Hs12o3kNnx2Gkw7Y4DAkhHQ3M81KSGvdhscDs8LNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:6o0rLtubZRN7c6SFXwrEiayv3fje678f6Ql0yDHTz+m73rWHhAZL1AW7FknEpJXeNEYdsgL46J3StFlaj2pSQDX0nxwDtWEdSw+aaJFsmBCdoGYFSvBwE08YTYw1GqgkdBY58S2/IFlNN3srzWoOOY+qSbV6VDMczZ/+oL5E30c=,iv:tMDGsPcew5UrgyF6uezq1/D7biYyEl6b0ANjcNzWr44=,tag:Qu/0pDuGazR7NKmxCw+vCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
