---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-leeward-backups.yaml
  - pvc-backup-cronjob.yaml
  - toolbox-pod.yaml
  - rclone-config-secret.sops.yaml
  - ./syncthing
