apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:W6XjA/W2LmeDY3l0Ms5W2xbOh4M3DlmsqfGLUoaectCMxEWV,iv:YK2xU6pcKkDeZzurq5zMOzgNsUIQzgXxILOjahOsNJ8=,tag:r87d+7mUQPvpwy/Qm2eEeA==,type:str]
    credentials.json: ENC[AES256_GCM,data:wxxoYZB+MRAmS5tfSA79MlhVWcn8d6zMlubifD6IRnqOG2Pg+HSd+vGV1P00Olm8RcPN69kT7ZuLUwtzBNur/5OMMsQwM5MSwjTEC4T1ZabQiI+BABmdo6ntJZmr6mdLMYbPkQCxMOP1T0hSDYT9jwUfgrsLJOzlRwe3W1EqIbl6+2lrdIuMTdwbG9DcWMZpZksmgTr15Ocn/ds5E4awwMMLSdDJPzTaF3g4TenOGg==,iv:XOYMFWY+fa4SKpbhC/8Mo/BDz9fL2KfHkF30H27eDLs=,tag:BqvMub6WkLJDXAf2Z1+S/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SVgrMWtEaXVXbmlEblVZ
            b3V3MnZyd0MvRVNRK2s3VnIrcElqczYyKzBrCkNtOU9JQTlJMVBhZy9VZ0VQd3A2
            S1dUSVlzMm9XNk1hZVREZUNjNWdFL3MKLS0tIGFjN0JnNjd1ci9EUmladk1QQUpI
            TU44QXRKUFVoVW9JRkpXem1NQjdoRXMKsSkw0wD9nkA5VJ6Kcv09RSl7ouvmeuwa
            WLRfWP2D+v41wDICWdxVteonHWg0c6sbH9OsbiXIOmsHXcAvjgUY+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:rSA8i51XEptkq5mzsvtfzJqCk97iT1Xpb6Lbmduj09KO2YwUSbSvkGT9bTRpchZv33jMst7N/67tMyFxw279RVbhvfcktLOxKOksdbAxq6Xfz8rwcGGECjd6f8YxDtZlQBTvK3CdGGUbRI4b9fRjYyTSP+fRNJ/eawlibsTamhY=,iv:CVyAIWoHi1Ue9zEAXScOtbg23VaP4Fr3ioB4X61BTIU=,tag:Njxz7PHWCVI9RH5dYmgo8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
