# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.22.0/_definitions.json#/definitions/io.k8s.api.core.v1.Secret
apiVersion: v1
kind: Secret
metadata:
    name: crunchy-postgres-secret
    namespace: database
stringData:
    s3.conf: ENC[AES256_GCM,data:0WO1xXieVZXVGVKjjiVXeHphEUZ+Xsyf52lNHJIq/Z9oUmTUDUGqP9Mteaf3fr7rBYwU7xoFc2RUr9iLuPb8Rpf3axXfgFQpVxeP+7981G853Vu5Xl43fpmDb0Xy5+fvmGtYOokdTaagsD+PsDoxJHHekX1xC+ObTQaXOa0DmV1T1dUaFRFK3pagr0izzNWWlmk0KVjjJq9h6gIEWvFafrYc8sJhxm3aQXNFhlg7Jj+enFLOlq5aq59S5ibQKFWlbRoQeFkEk3z14roxZqEzTtg=,iv:z3EB7xFTDpb6M6P+KoeerNzM6LvVzqBLHfnA30qm/DQ=,tag:gqJtJeyRoYj6xVxwNa3NLw==,type:str]
    encryption.conf: ENC[AES256_GCM,data:2afKR9wPAWDWuKLWIHULDuw9696IaY7WZV6EJG0BlFyy8mw/MactHwP+isKIzqQyXm1cb3FbYMDbNkV8ShfkyQs=,iv:G427S3T8eHwjH8PPmxKre3xSornUokIst0dYED2dBFQ=,tag:VMdUcfsKHJrNhp97C17ddg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTUQ5RjJiSUJidWluYVor
            Nm5Wb2dKTXo5c0J2cFFiV1BzMTArZUNHNmkwCkNmZGNyOUl1d3hkT2lzdnpXRkg4
            ZlJrV09xVE84MlVpcHNycVFzV1JnLzAKLS0tIFptVENrNUdDZkZkQmpJK1VJSzFH
            TTBJVUhrY1o1bi9nWEdRaUo4endLbmMKgAFihqcgGmh5Prf0bcPu3sCyfXsKZSsg
            1fpkrJc/WiyyIxgYeuM5FQpVJH8D5KTXWtubwoftlVadKj0SJBpn7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:30:49Z"
    mac: ENC[AES256_GCM,data:XnT0HXkYGw7G/FvFCmLg5uhnXddwaWtQtEby0FmVvgnLEIw9G9QadF2t/2V3MhSWYR1+gPnMrZME1ajlYKib2xwOUwowmFTIFnqMm9mJ9KkfCswCMT0vivtcxgsGYNXNGlZU1r/5g/qjttsklmhHnFQiKzQoQG241NdEoE4r0Y8=,iv:DitiR4r6VgmHQKIAySBNsUbqCMWT6QKvKHZ/bDx3bi8=,tag:WWBAW2+YkCWkUQtnnDXvVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
