apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-titan-nvme
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.20.30.99
  share: /volume1/k8s
reclaimPolicy: Delete
volumeBindingMode: Immediate
